version: '3.9'

services:
  postgres:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_DB: 'gpt-bot-testdb'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '111555111'
    ports:
      - '5432:5432'
    volumes:
      - ./local_database/ro:/ro:ro
      - ./local_database/rw:/rw
      - ./local_database/Downloads:/dl:ro
      - ./local_database/.data/pg13:/var/lib/postgresql/data
    container_name: gpt-bot-testdb